# Generated by Django 5.2.3 on 2026-02-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='flowrate',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='temperature',
        ),
        migrations.AddField(
            model_name='equipment',
            name='condition',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
